language: rust
rust:
  - nightly
sudo: required
before_install:
  - wget http://www-labs.iro.umontreal.ca/~simul/testu01/TestU01-1.2.3.zip
  - unzip TestU01-1.2.3.zip
  - cd TestU01-1.2.3 && ./configure --prefix=/usr && make && sudo make install
